In [ ]:
from google.colab import files

uploaded = files.upload()

Saving BankChurners.csv to BankChurners.csv

In [ ]:
import pandas as pd
pd.set_option('display.max_columns', None)
df = pd.read_csv('BankChurners.csv')
df.head(10)

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,5,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.99991
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.99994
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.99998
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,3,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.99987
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,5,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.99998
5,713061558,Existing Customer,44,M,2,Graduate,Married,$40K - $60K,Blue,36,3,1,2,4010.0,1247,2763.0,1.376,1088,24,0.846,0.311,0.000055,0.99994
6,810347208,Existing Customer,51,M,4,Unknown,Married,$120K +,Gold,46,6,1,3,34516.0,2264,32252.0,1.975,1330,31,0.722,0.066,0.000123,0.99988
7,818906208,Existing Customer,32,M,0,High School,Unknown,$60K - $80K,Silver,27,2,2,2,29081.0,1396,27685.0,2.204,1538,36,0.714,0.048,0.000086,0.99991
8,710930508,Existing Customer,37,M,3,Uneducated,Single,$60K - $80K,Blue,36,5,2,0,22352.0,2517,19835.0,3.355,1350,24,1.182,0.113,0.000045,0.99996
9,719661558,Existing Customer,48,M,2,Graduate,Single,$80K - $120K,Blue,36,6,3,3,11656.0,1677,9979.0,1.524,1441,32,0.882,0.144,0.000303,0.99970

**CLIENTNUM** Номер клиента. Уникальный идентификатор клиента, у которого открыт счет.  
**Attrition_Flag** Переменная внутреннего события (активности клиента) - если счет закрыт, то 1, иначе 0.  
**Customer_Age** Демографическая переменная — возраст клиента в годах  
**Gender** Демографическая переменная - M=мужчина, F=женщина.  
**Dependent_count** Демографическая переменная – количество иждивенцев.  
**Education_Level** Демографическая переменная — образовательный уровень владельца счета.  
**Marital_Status** Демографическая переменная: женат, холост, разведен, неизвестен.  
**Income_Category** Демографическая переменная — категория годового дохода владельца счета.  
**Card_Category** Переменная продукта — тип карты (синяя, серебряная, золотая, платиновая).  
**Months_on_book** Период сотрудничества с банком.  
**Total_Relationship_Count** Общее количество продуктов/услуг, связанных с клиентом.  
**Months_Inactive_12_mon** Количество месяцев бездействия клиента за последние 12 месяцев.  
**Contacts_Count_12_mon** Общее количество контактов с клиентом за последние 12 месяцев.  
**Credit_Limit** Кредитный лимит клиента.  
**Total_Revolving_Bal** Общая сумма задолженности клиента по кредитным картам.  
**Avg_Open_To_Buy** Средняя доступная сумма для использования по кредитной карте.  
**Total_Amt_Chng_Q4_Q1** Изменение общей суммы транзакций между четвертями 4 и 1 (обычно между октябрем и январем).  
**Total_Trans_Amt** Общая сумма транзакций клиента.  
**Total_Trans_Ct** Общее количество транзакций клиента.  
**Total_Ct_Chng_Q4_Q1** Изменение общего количества транзакций между четвертями 4 и 1.  
**Avg_Utilization_Ratio** Среднее использование кредитной карты клиентом.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 23 columns):
 #   Column                                                                                                                              Non-Null Count  Dtype
---  ------                                                                                                                              --------------  -----
 0   CLIENTNUM                                                                                                                           10127 non-null  int64
 1   Attrition_Flag                                                                                                                      10127 non-null  object
 2   Customer_Age                                                                                                                        10127 non-null  int64
 3   Gender                                                                                                                              10127 non-null  object
 4   Dependent_count                                                                                                                     10127 non-null  int64
 5   Education_Level                                                                                                                     10127 non-null  object
 6   Marital_Status                                                                                                                      10127 non-null  object
 7   Income_Category                                                                                                                     10127 non-null  object
 8   Card_Category                                                                                                                       10127 non-null  object
 9   Months_on_book                                                                                                                      10127 non-null  int64
 10  Total_Relationship_Count                                                                                                            10127 non-null  int64
 11  Months_Inactive_12_mon                                                                                                              10127 non-null  int64
 12  Contacts_Count_12_mon                                                                                                               10127 non-null  int64
 13  Credit_Limit                                                                                                                        10127 non-null  float64
 14  Total_Revolving_Bal                                                                                                                 10127 non-null  int64
 15  Avg_Open_To_Buy                                                                                                                     10127 non-null  float64
 16  Total_Amt_Chng_Q4_Q1                                                                                                                10127 non-null  float64
 17  Total_Trans_Amt                                                                                                                     10127 non-null  int64
 18  Total_Trans_Ct                                                                                                                      10127 non-null  int64
 19  Total_Ct_Chng_Q4_Q1                                                                                                                 10127 non-null  float64
 20  Avg_Utilization_Ratio                                                                                                               10127 non-null  float64
 21  Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1  10127 non-null  float64
 22  Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2  10127 non-null  float64
dtypes: float64(7), int64(10), object(6)
memory usage: 1.8+ MB

In [ ]:
df['Attrition_Flag'].value_counts()

Attrition_Flag
Existing Customer    8500
Attrited Customer    1627
Name: count, dtype: int64

In [ ]:

duplicate_rows = df[df.duplicated(['CLIENTNUM'], keep=False)]

# Если есть дубликаты, вывести их
if not duplicate_rows.empty:
    print("Найдены дубликаты в столбце CLIENTNUM:")
    print(duplicate_rows)

    # Вывести сами дублирующиеся ClientNUM значения
    duplicated_clientnums = df[df.duplicated(['CLIENTNUM'], keep=False)]['CLIENTNUM'].unique()
    print("Дублирующиеся значения CLIENTNUM:")
    for num in duplicated_clientnums:
        print(num)
else:
    print("Дубликаты в столбце CLIENTNUM не найдены.")

Дубликаты в столбце CLIENTNUM не найдены.

In [ ]:
df = df.drop('CLIENTNUM', axis=1)

In [ ]:
df['Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2'].describe()

count    10127.000000
mean         0.840003
std          0.365301
min          0.000420
25%          0.999660
50%          0.999820
75%          0.999900
max          0.999990
Name: Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2, dtype: float64

In [ ]:
df['Income_Category'].value_counts()

Income_Category
Less than $40K    3561
$40K - $60K       1790
$80K - $120K      1535
$60K - $80K       1402
Unknown           1112
$120K +            727
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score

df['Attrition_Flag'] = df['Attrition_Flag'].map({'Existing Customer': 0, 'Attrited Customer': 1})

# Разделим входные данные на признаки (X) и целевую переменную (y)
X = df.drop('Attrition_Flag', axis=1)
y = df['Attrition_Flag']

# Разделение на обучающую и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Определение числовых и категориальных признаков
numeric_features = ['Total_Trans_Ct', 'Total_Trans_Amt', 'Avg_Open_To_Buy', 'Total_Revolving_Bal', 'Credit_Limit', 'Months_on_book', 'Customer_Age']
categorical_features = ['Gender', 'Education_Level', 'Marital_Status', 'Income_Category', 'Card_Category']

# Определение трансформеров для числовых и категориальных признаков
numeric_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Создание предобработчика
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Создание финального пайплайна
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', GradientBoostingClassifier())
])

# Кросс-валидация на обучающем наборе
scores = cross_val_score(model, X_train, y_train, cv=5)
print("Средняя точность на кросс-валидации обучающего набора:", scores.mean())
print("Отклонение точности на кросс-валидации обучающего набора:", scores.std())

# Финальная оценка на отложенном тестовом наборе
model.fit(X_train, y_train)
final_test_accuracy = model.score(X_test, y_test)
print("Точность на финальном тестовом наборе:", final_test_accuracy)

Средняя точность на кросс-валидации обучающего набора: 0.9407496515639637
Отклонение точности на кросс-валидации обучающего набора: 0.006999971180467175
Точность на финальном тестовом наборе: 0.941263573543929

In [ ]:
# Создание финального пайплайна с настроенным бустингом
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', GradientBoostingClassifier(n_estimators=200, learning_rate=0.1))
])

# Кросс-валидация на обучающем наборе
scores = cross_val_score(model, X_train, y_train, cv=5)
print("Средняя точность на кросс-валидации обучающего набора:", scores.mean())
print("Отклонение точности на кросс-валидации обучающего набора:", scores.std())

# Финальная оценка на отложенном тестовом наборе
model.fit(X_train, y_train)
final_test_accuracy = model.score(X_test, y_test)
print("Точность на финальном тестовом наборе:", final_test_accuracy)

Средняя точность на кросс-валидации обучающего набора: 0.9454400956580681
Отклонение точности на кросс-валидации обучающего набора: 0.005459057907175975
Точность на финальном тестовом наборе: 0.93928923988154

**больше не значит лучше**